version: "3"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: ["sh", "-c", "while [ 0 ]; do date; sleep 30 ; done"]
    env_file:
      - .env
    depends_on:
      - sqldb
    expose:
      - "8000"
    ports:
      - 8000:8000
    volumes:
      - ./zeroxchat:/usr/local/app/
  sqldb:
    image: postgres:13-alpine
    container_name: sqldb
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
        - ./postgres-data:/var/lib/postgresql

  redischat:
    image: redis:6-alpine
    container_name: redischat
    command: ["redis-server", "/usr/local/etc/redis/master.conf"]
    volumes:
        - ./:/usr/local/etc/redis/
